Add preStop hook to gitgc cronjobs to log kernel errors and warnings
We sometimes observe git gc failing with errors like:

error: pack-objects died of signal 7
fatal: failed to run repack

Logging kernel errors and warnings may help to find the root cause of
these failures.

Change-Id: I3ad669a181063e4ed63deca42162bbd14ae80900